# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GMLEditor
                                 A QGIS plugin
 Wtyczka umożliwia edytowanie plików GML w schemacie BDOT10k
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-10-01
        copyright            : (C) 2026 by JanPaJ
        email                : patryk4857@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GMLEditor class from file GMLEditor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GMLEditor import GMLEditor
    return GMLEditor(iface)
